theme: minima
title: Tennessee Tough Questions

posts:
  - _posts/2025-01-30-Abortion Questions.md
  - _posts/2025-02-06-Immigration-Resources.md
  - _posts/2025-02-26-Gender-Affirming-Care-Questions.md
  - _posts/2026-2-5-ICE-Questions.md
  
nav:
  - name: Home
    url: "/"
  - name: Immigration Resources
    url: "/2025-02-06-Immigration-Resources"
  - name: Gender Affirming Care Questions
    url: "/2025-02-26-Gender-Affirming-Care-Questions"
